SELECT
    MobileMessageTrackingID
    , EID
    , MID
    , Mobile
    , MessageID
    , KeywordID
    , CodeID
    , ConversationID
    , CampaignID
    , Sent
    , Delivered
    , Undelivered
    , Unsub
    , OptIn
    , OptOut
    , Outbound
    , Inbound
    , CreateDateTime
    , ModifiedDateTime
    , ActionDateTime
    , MessageText
    , IsTest
    , MobileMessageRecurrenceID
    , ResponseToMobileMessageTrackingID
    , IsValid
    , InvalidationCode
    , SendID
    , SendSplitID
    , SendSegmentID
    , SendJobID
    , SendGroupID
    , SendPersonID
    , SubscriberID 
    , SubscriberKey
    , SMSStandardStatusCodeID
    , Description
    , Name
    , ShortCode
    , SharedKeyword
    , Ordinal
    , FromName
FROM _smsMessageTracking